import pandas as pd

# Read raw stock data
df = pd.read_csv("data/reliance_stock_data.csv")

print("Raw Data Preview:")
print(df.head())

# Standardize column names
df.columns = [
    "date",
    "close",
    "high",
    "low",
    "open",
    "volume"
]

# Convert numeric columns properly
numeric_columns = [
    "close",
    "high",
    "low",
    "open",
    "volume"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Convert date column to datetime
df["date"] = pd.to_datetime(df["date"])

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Create daily return percentage
df["daily_return_pct"] = (
    df["close"].pct_change() * 100
)

# Create 7-day moving average
df["moving_avg_7"] = (
    df["close"].rolling(window=7).mean()
)

# Fill null values generated by rolling average
# Fill only numeric null values
numeric_fill_cols = [
    "daily_return_pct",
    "moving_avg_7"
]

df[numeric_fill_cols] = (
    df[numeric_fill_cols].fillna(0)
)
# Save transformed dataset
df.to_csv(
    "data/reliance_stock_transformed.csv",
    index=False
)

print("\nTransformation completed successfully!")
print(df.head())